name: cloud_storage_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_storage: ^12.1.0
  firebase_ui_storage: ^2.0.5
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  get: ^4.6.6
  keyboard_dismisser: ^3.0.0
  mime: ^1.0.5
  mimecon: ^1.0.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
